name: Build Client

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r ./client/requirements.txt

      - name: Build executable with PyInstaller
        run: |
          python -m nuitka --standalone --onefile --disable-console --include-data-file=./client/vpn/windows/windows_vpn.dll --plugin-enable=kivy ./client/client.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: client.exe
          path: ./client/client.exe
